### ISSUE TITLE
AcknowledgeMessage task is not available in Frends

### ISSUE THREAD

**Issue by levik-buka** [CommunityHiQ/Frends.Community.RabbitMQ#17]
I imported RabbitMQ task library to Frends, but I don't see public static void AcknowledgeMessage(ManualAckType ackType, ulong deliveryTag) in the list of tasks. Is this because it is void?

![image](https://user-images.githubusercontent.com/1180026/112625775-064db200-8e38-11eb-803c-b1fd5cbcc7d8.png)

My RabbitMQ versio is 1.4.3, which is based on master 1.4.0. I just had to increase minor number, so I could import the library after small changes.

Br,
Lev

**Comment by OssiGalkin** [comment]
Hi! 

Yeah if it returns void, frends won't show it as a task. Void would make certain things like logging and #result odd/hard to use/implement.

**Comment by OssiGalkin** [comment]
Fixed in pr #21 (or version 1.6.0)
