### ISSUE TITLE
HostName is not a secret

### ISSUE THREAD

**Issue by levik-buka** [CommunityHiQ/Frends.Community.RabbitMQ#18]
Hi,
Should HostName be decorated with [PasswordPropertyText] attribute, so the password will not leak to logs if used ConnectWithURI = true? Or how to do if ConnectWithURI = false, then HostName would be normal, but if true, then HostName would be a secret?

Br,
Lev

**Comment by OssiGalkin** [comment]
This is fixed in pr #21 (or version 1.6.0). HostName name is now secret.
